@startuml

map log {
	type => "in" or "out"
	tag_id => foreign_key
	time => datetime
}

map tag {
	id => ID
	person_id => foreign_key
	name => text
}

map person {
	id => ID
	name => text
}

map membership {
	person_id => foreign_key
	subteam_id => foreign_key
	job_id => foreign_key
	starting_from => datetime
}

map subteam {
	id => ID
	name => text
}

map job {
	id => ID
	name => text
	quota_hours_per_week => int
}

log::tag_id		}-||	tag::id
tag::person_id		}-||	person::id

membership::person_id	}-u-||	person::id
membership::subteam_id	}-l-||	subteam::id
membership::job_id	}-||	job::id

@enduml
