# Generated by Django 5.2.5 on 2025-09-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='subteam_id',
        ),
    ]
