# Generated by Django 5.2.5 on 2025-09-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0002_remove_person_subteam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='subteam_id',
            field=models.ManyToManyField(to='webui.subteam'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
