# Generated by Django 5.2.5 on 2025-09-04 08:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webui', '0003_person_subteam_id_delete_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField()),
                ('quota', models.IntegerField(verbose_name='Quota (hours per week)')),
            ],
        ),
        migrations.RenameField(
            model_name='log',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='person',
            name='subteam_id',
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(
                choices=[
                    ('IN', 'Check-in'),
                    ('OUT', 'Check-out'),
                    ('WTF', 'Card not linked'),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='name',
            field=models.CharField(),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'starting_from',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    'job',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='webui.job',
                    ),
                ),
                (
                    'person',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='memberships',
                        to='webui.person',
                    ),
                ),
                (
                    'subteam',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='members',
                        to='webui.subteam',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('tag', models.BinaryField()),
                ('name', models.CharField()),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tags',
                        to='webui.person',
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='tag',
            field=models.ForeignKey(
                default=b'',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='logs',
                to='webui.tag',
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TagPerson',
        ),
    ]
