# Generated by Django 5.2.5 on 2025-09-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webui', '0008_alter_log_time_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='average_week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_minutes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
