# Generated by Django 5.2.5 on 2025-09-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webui', '0009_statistics_average_week_statistics_total_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
