# Generated by Django 5.2.5 on 2025-09-11 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webui', '0010_alter_tag_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='scanner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='logs',
                to='webui.scanner',
            ),
        ),
    ]
