# Generated by Django 5.2.5 on 2025-09-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webui', '0011_scanner_log_scanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(
                choices=[
                    ('IN', 'Check-in'),
                    ('OUT', 'Check-out'),
                    ('WTF', 'Card not linked'),
                    ('REG', 'Card registered'),
                ],
                max_length=3,
            ),
        ),
    ]
